# Run tests against the MATLAB Language Grammar

name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 14.x, 18.x]
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install system dependencies
        run: sudo apt-get -y install libxml2-utils
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Tests
        run: npm test